apiVersion: apps/v1
kind: Deployment
metadata:
  name: cl-be
  namespace: 
  labels:
    app: cl-be
    tier: backend
    version: v1.0
    name: cl-be
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cl-be
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: cl-be
        tier: backend
        version: v1.0
    spec:
      containers:
        - name: burger-builder-backend
          image: afnanjk2017/burger-backend:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: db-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: db-port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: db-name
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: db-password
            - name: DB_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: db-driver
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: spring-profile
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
