apiVersion: apps/v1
kind: Deployment
metadata:
  name: cl-fe
  namespace: 
  labels:
    app: cl-fe
    tier: frontend
    version: v1.0
    name: cl-fe

  #annotations for prometehus here

  
    
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cl-fe
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 25%
  template: 
    metadata:
      labels:
        app: cl-fe
        tier: frontend
        version: v1.0
    spec:
      containers:
        - name: catus-locatus-fe
          image: afnanjk2017/burger-frontend:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "100Mi"
              cpu: "100m"    
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe: 
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5