apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: external-dns
  namespace: kube-system
spec:
  chart: external-dns
  repo: https://charts.bitnami.com/bitnami
  targetNamespace: kube-system
  valuesContent: |-
    provider: azure

    azure:
     

    # RBAC
    serviceAccount:
      create: false
      name: external-dns

    policy: sync
    txtOwnerId: aks-norah-g6
    sources:
      - ingress
    domainFilters: []
    interval: 1m
    logLevel: info
